import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/Web")
public class Web extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        
        // HTML content generated by the servlet
        out.println("<html>");
        out.println("<head><title>More About DevOps</title></head>");
        out.println("<body>");
        out.println("<h1>More Information About DevOps</h1>");
        out.println("<p>DevOps helps to bridge the gap between development and operations, promoting better collaboration.</p>");
        out.println("<p>It supports Continuous Integration and Continuous Deployment (CI/CD), ensuring faster and more reliable software releases.</p>");
        out.println("<p>DevOps tools like Jenkins, Docker, Kubernetes, and Ansible play a significant role in automating these processes.</p>");
        out.println("<br><a href='index.html'>Back to Home</a>");
        out.println("</body>");
        out.println("</html>");
    }
}

